### ISSUE TITLE
Account Creation

### ISSUE THREAD

**Issue by Cragsdale1996** [Thakugan/hooplife#10]
As a user, I want to be able to create an account so that I can use HoopLife

Need a view dedicated to create an account
Need a username input field
Need a password input field
Need a confirm password input field
Need an email input field
Need a first name input field
Need a last name input field
Fields need validation so improper values are not submitted
Need a “Create Account” button
Need a “Already have an account? Login” hyperlink that redirects to the login view
When I click submit, I am redirected to the login page.

**Comment by Thakugan** [comment]
There is currently an issue with preflight stuff. Fixing this will be part of our backlog for now.
